GOOGLE_CREDENTIAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/.credentials/football-analytics-platform-fdf39ee7f4bb.json"
BUCKET_NAME: "football-analytics-platform"
JOBS:
  - SEASON: "2021"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/test/2021_E0.csv"
    DESTINATION_BLOB_PATH: "test/2021_E0.csv"
  - SEASON: "1920"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/test/1920_E0.csv"
    DESTINATION_BLOB_PATH: "test/1920_E0.csv"
  - SEASON: "1819"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/test/1819_E0.csv"
    DESTINATION_BLOB_PATH: "test/1819_E0.csv"
  - SEASON: "1718"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/test/1718_E0.csv"
    DESTINATION_BLOB_PATH: "test/1718_E0.csv"
  - SEASON: "1617"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/test/1617_E0.csv"
    DESTINATION_BLOB_PATH: "test/1617_E0.csv"
  - SEASON: "1516"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/test/1516_E0.csv"
    DESTINATION_BLOB_PATH: "test/1516_E0.csv"                    
