GOOGLE_CREDENTIAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/.credentials/football-analytics-platform-fdf39ee7f4bb.json"
BUCKET_NAME: "football-analytics-platform"
JOBS:
  - SEASON: "2021"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/2021_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/2021_E0.csv"
  - SEASON: "1920"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/1920_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/1920_E0.csv"
  - SEASON: "1819"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/1819_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/1819_E0.csv"
  - SEASON: "1718"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/1718_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/1718_E0.csv"
  - SEASON: "1617"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/1617_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/1617_E0.csv"
  - SEASON: "1516"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/1516_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/1516_E0.csv"
  - SEASON: "1415"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/1415_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/1415_E0.csv"
  - SEASON: "1314"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/1314_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/1314_E0.csv"
  - SEASON: "1213"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/1213_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/1213_E0.csv"
  - SEASON: "1112"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/1112_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/1112_E0.csv"
  - SEASON: "1011"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/1011_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/1011_E0.csv"
  - SEASON: "0910"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/0910_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/0910_E0.csv"
  - SEASON: "0809"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/0809_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/0809_E0.csv"
  - SEASON: "0708"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/0708_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/0708_E0.csv"
  - SEASON: "0607"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/0607_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/0607_E0.csv"
  - SEASON: "0506"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/0506_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/0506_E0.csv"
  - SEASON: "0405"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/0405_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/0405_E0.csv"
  - SEASON: "0304"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/0304_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/0304_E0.csv"
  - SEASON: "0203"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/0203_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/0203_E0.csv"
  - SEASON: "0102"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/0102_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/0102_E0.csv"
  - SEASON: "0001"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/0001_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/0001_E0.csv"
  - SEASON: "9900"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/9900_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/9900_E0.csv"
  - SEASON: "9899"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/9899_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/9899_E0.csv"
  - SEASON: "9798"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/9798_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/9798_E0.csv"
  - SEASON: "9697"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/9697_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/9697_E0.csv"
  - SEASON: "9596"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/9596_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/9596_E0.csv"
  - SEASON: "9495"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/9495_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/9495_E0.csv"
  - SEASON: "9394"
    DIVISION: "E0"
    LOCAL_PATH: "/home/jon-dev/Workbench/Projects/football-analytics-platform/data/landing/football-data-uk/9394_E0.csv"
    DESTINATION_BLOB_PATH: "landing/football-data-uk/9394_E0.csv"
    